M48
; DRILL file {KiCad 7.0.1} date Wed Mar 29 21:52:52 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-29T21:52:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X100.699Y-118.76
X105.549Y-118.76
T2
X100.399Y-121.79
X105.849Y-121.79
T0
M30
